name: yaepub
description: A simple, lightweight and robust Dart package for parsing EPUB files, extracting metadata, chapters, and content to build e-book readers.
version: 1.0.1
repository: https://github.com/renanyoy/yaepub

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  path: ^1.9.1
  crypto: ^3.0.7
  xml: ^6.6.1
  archive: ^4.0.9
  mime_type: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
